# Site settings
title: "Cup of Cloud"
description: "A casual podcast about Azure"
podcast-description: "A casual podcast about Azure and the tech community"
url:  "cupof.cloud" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: " Cup Of Cloud"
  email: ""
  url: ""
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: CupofCloud_
  card: summary
facebook:
  app_id: 
logo: /assets/img/cup_of_cloud_logo.png
social:
  name: 
  links:
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Cup of CLoud
podcast_author: Karl Cooke, Simon Lee, and Chris Wright
podcast_email: 
podcast_subtitle: "A casual podcast about Azure and the tech community"
podcast_summary: "A casual podcast about Azure and the tech community"
podcast_description: "A casual podcast about Azure and the tech community"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2019-07-20" #Launch date of your podcast
podcast_copyright: "&#xA9;Cup of Cloud"
podcast_feed: 
podcast_artwork: "/assets/img/cup_of_cloud_logo.png"